Fix crash on binding singleton service
2022-05-06 18:51:39.641 641-819/system_process W/ActivityManager: Permission Denial: Accessing service com.hp.multiuserawareapptest/.SingletonService from pid=6417, uid=1010187 that is not exported from uid 1010186
2022-05-06 18:51:39.642 6417-6417/com.hp.multiuserawareapptestclient D/AndroidRuntime: Shutting down VM
2022-05-06 18:51:39.643 6417-6417/com.hp.multiuserawareapptestclient E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.hp.multiuserawareapptestclient, PID: 6417
    java.lang.RuntimeException: Unable to resume activity {com.hp.multiuserawareapptestclient/com.hp.multiuserawareapptestclient.MainActivity}: java.lang.SecurityException: Not allowed to bind to service Intent { cmp=com.hp.multiuserawareapptest/.SingletonService }
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4438)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4470)
        at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7664)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
     Caused by: java.lang.SecurityException: Not allowed to bind to service Intent { cmp=com.hp.multiuserawareapptest/.SingletonService }
        at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1838)
        at android.app.ContextImpl.bindService(ContextImpl.java:1749)
        at android.content.ContextWrapper.bindService(ContextWrapper.java:756)
        at android.content.ContextWrapper.bindService(ContextWrapper.java:756)
        at com.hp.multiuserawareapptestclient.MainActivity$MyServiceConnection.connect(MainActivity.java:109)
        at com.hp.multiuserawareapptestclient.MainActivity.onResume(MainActivity.java:66)
        at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1456)
        at android.app.Activity.performResume(Activity.java:8129)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4428)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4470) 
        at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52) 
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.app.ActivityThread.main(ActivityThread.java:7664) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947) 